### ISSUE TITLE
Node v16+ support

### ISSUE THREAD

**Issue by alexcastillo** [avz/node-posix-clock#16]
Hi,

Thanks again for this project! We've been using it for many years.

We are trying to upgrade to Node v16-19+, I noticed node-posix-clock is incompatible. Here are the errors I'm getting:

```
> posix-clock@2.0.0 install /Users/**/*/node_modules/posix-clock
> node-gyp rebuild

  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  LIBTOOL-STATIC Release/nothing.a
env: python: No such file or directory
make: *** [Release/nothing.a] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 21.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/**/*/node_modules/posix-clock
gyp ERR! node -v v12.22.7
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN notsup Unsupported engine for @fastify/busboy@1.2.1: wanted: {"node":">=14"} (current: {"node":"12.22.7","npm":"6.14.15"})
npm WARN notsup Not compatible with your version of node/npm: @fastify/busboy@1.2.1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! posix-clock@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the posix-clock@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/***/.npm/_logs/2023-01-28T00_00_18_341Z-debug.log
```

**Comment by alexcastillo** [comment]
EDIT:

(with node 14)

```
npm install

> posix-clock@2.0.0 install /Users/***/node_modules/posix-clock
> node-gyp rebuild

  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/src/nothing.o
  LIBTOOL-STATIC Release/nothing.a
env: python: No such file or directory
make: *** [Release/nothing.a] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Darwin 21.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/***/node_modules/posix-clock
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! posix-clock@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the posix-clock@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by avz** [comment]
Hi Alex. 
I was not able to reproduce exactly your error, I suspect that it is related to the peculiarities of the python installation in your OS.

However, I updated the build dependencies and released version 3.0.0. Try it, please.

**Comment by alexcastillo** [comment]
@avz,

As always, thank you so much for the timely response. I really appreciate it 🙏🏼

I'll give this a try as soon as possible.

Best,
Alex

**Comment by biasedbit** [comment]
@alexcastillo Looks like a missing binary (or symlink) for python3 available in `$PATH`. What do you get when running `which python && python --version`?

Just a heads up that latest python3 (3.11.x) didn't work for me; I had to downgrade to 3.10; the error I got on 3.11 was:

```
> posix-clock@2.0.0 install (...)/node_modules/posix-clock
> node-gyp rebuild

(...)

    build_file_contents = open(build_file_path, 'rU').read()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
```
